export const serviceTiles = [
  {
    id: 1,
    name: "Carpenter",
    image: require("../images/serviceTileLogos/carpenter.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 2,
    name: "Electrician",
    image: require("../images/serviceTileLogos/electrician.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 3,
    name: "Water Geyser",
    image: require("../images/serviceTileLogos/geyser.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 4,
    name: "Paint Job",
    image: require("../images/serviceTileLogos/paint.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 5,
    name: "Plumbing",
    image: require("../images/serviceTileLogos/plumbing.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 6,
    name: "Solar Panels",
    image: require("../images/serviceTileLogos/solar.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 7,
    name: "Welding",
    image: require("../images/serviceTileLogos/welding.jpg"),
    category: "Home Appliance Maintenance",
  },
  {
    id: 8,
    name: "Hair Care",
    image: require("../images/serviceTileLogos/beauty-hairCare.jpg"),
    category: "Beauty And Personal Care",
  },
  {
    id: 9,
    name: "Make-Up",
    image: require("../images/serviceTileLogos/beauty-makeup.jpg"),
    category: "Beauty And Personal Care",
  },
  {
    id: 10,
    name: "Skin Care",
    image: require("../images/serviceTileLogos/beauty-skinCare.jpg"),
    category: "Beauty And Personal Care",
  },
  {
    id: 11,
    name: "Men Clothes",
    image: require("../images/serviceTileLogos/tailoring-men.jpg"),
    category: "Tailoring",
  },
  {
    id: 12,
    name: "Women Attire",
    image: require("../images/serviceTileLogos/tailoring-women.jpg"),
    category: "Tailoring",
  },
  {
    id: 13,
    name: "Brake And Tires",
    image: require("../images/serviceTileLogos/car-brakeAndTire.jpg"),
    category: "Vehicle Maintenance",
  },
  {
    id: 14,
    name: "General Car Care",
    image: require("../images/serviceTileLogos/car-generalMaintenance.jpg"),
    category: "Vehicle Maintenance",
  },
  {
    id: 15,
    name: "Mechanic At Home",
    image: require("../images/serviceTileLogos/car-MaintenanceAtHome.jpg"),
    category: "Vehicle Maintenance",
  },
  {
    id: 16,
    name: "Women Attire",
    image: require("../images/serviceTileLogos/rent-womenAttireRenting.jpg"),
    category: "Attire Renting",
  },
  {
    id: 17,
    name: "Kids Attire",
    image: require("../images/serviceTileLogos/rent-KidsAttireRenting.jpg"),
    category: "Attire Renting",
  },
];

export const services = [
  {
    id: 1,
    serviceFrom: "Carpenter",
    name: "Furniture Repair",
    sale: 0,
    shopkeeper: "Person 1",
    price: 2000,
    image: require("../images/specificServices/furnitureRepair.jpg"),
  },
  {
    id: 2,
    serviceFrom: "Carpenter",
    name: "Custom Furniture",
    sale: 10,
    shopkeeper: "Person 2",
    price: 10000,
    image: require("../images/specificServices/customFurniture.jpg"),
  },
  {
    id: 3,
    serviceFrom: "Carpenter",
    name: "Furniture Installation",
    sale: 5,
    shopkeeper: "Person 3",
    price: 500,
    image: require("../images/specificServices/furnitureInstallation.jpg"),
  },
  {
    id: 4,
    serviceFrom: "Make-Up",
    name: "Bridal Makeup",
    sale: 0,
    shopkeeper: "Person 5",
    price: 5000,
    image: require("../images/specificServices/beauty/bridalMakeup.jpg"),
  },
  {
    id: 5,
    serviceFrom: "Make-Up",
    name: "Nail Polish",
    sale: 0,
    shopkeeper: "Person 5",
    price: 400,
    image: require("../images/specificServices/beauty/nailPolish.jpg"),
  },
  {
    id: 6,
    serviceFrom: "Hair Care",
    name: "Hair Styling",
    sale: 0,
    shopkeeper: "Person 5",
    price: 400,
    image: require("../images/specificServices/beauty/hairStyling.jpg"),
  },
  {
    id: 7,
    serviceFrom: "Hair Care",
    name: "Hair Coloring",
    sale: 15,
    shopkeeper: "Person 5",
    price: 900,
    image: require("../images/specificServices/beauty/hairColoring.jpg"),
  },
  {
    id: 8,
    serviceFrom: "Hair Care",
    name: "Hair Cutting",
    sale: 30,
    shopkeeper: "Person 5",
    price: 800,
    image: require("../images/specificServices/beauty/hairCutting.jpg"),
  },
  {
    id: 8,
    serviceFrom: "Skin Care",
    name: "Manicure",
    sale: 10,
    shopkeeper: "Person 7",
    price: 1400,
    image: require("../images/specificServices/beauty/manicure.jpg"),
  },
  {
    id: 8,
    serviceFrom: "Skin Care",
    name: "Pedicure",
    sale: 45,
    shopkeeper: "Person 8",
    price: 3000,
    image: require("../images/specificServices/beauty/pedicure.jpg"),
  },
];

export const featured = [
  {
    id: 1,
    name: "Some Shirt",
    shopkeeper: "Some Shopkeeper",
    sale: 10,
    image: require("../images/dashboardCarouselImages/carouselAd1.jpg"),
  },
  {
    id: 2,
    name: "Some Shirt",
    shopkeeper: "Some Shopkeeper",
    sale: 10,
    image: require("../images/dashboardCarouselImages/carouselAd2.jpg"),
  },
  {
    id: 3,
    name: "Some Shirt",
    shopkeeper: "Some Shopkeeper",
    sale: 0,
    image: require("../images/dashboardCarouselImages/carouselAd3.jpg"),
  },
];

// export const products = [
//   {
//     id: 1,
//     category: "Beauty",
//     itemName: "Concealer",
//     description: "some description",
//     price: 100,
//     image: require("../images/productImages/beauty1.jpg"),
//     sale: 10,
//     shopkeeper: "Dior",
//   },
//   {
//     id: 2,
//     category: "Beauty",
//     itemName: "Concealer",
//     description: "some description",
//     price: 200,
//     image: require("../images/productImages/beauty2.jpg"),
//     sale: 30,
//     shopkeeper: "Dior",
//     featured: true,
//   },
//   {
//     id: 3,
//     category: "Beauty",
//     itemName: "Prime Concealer",
//     description: "some description",
//     price: 300,
//     image: require("../images/productImages/beauty3.jpg"),
//     sale: 15,
//     shopkeeper: "Dior",
//     featured: true,
//   },
//   {
//     id: 4,
//     category: "Beauty",
//     itemName: "Lipstick Kit",
//     description: "some description",
//     price: 700,
//     image: require("../images/productImages/beauty4.jpg"),
//     sale: 0,
//     shopkeeper: "Dior",
//   },
//   {
//     id: 5,
//     category: "Beauty",
//     itemName: "Brush kit",
//     description: "some description",
//     price: 300,
//     image: require("../images/productImages/beauty5.jpg"),
//     sale: 20,
//     shopkeeper: "Dior",
//     featured: true,
//   },
//   {
//     id: 6,
//     category: "Beauty",
//     itemName: "Brush",
//     description: "some description",
//     price: 700,
//     image: require("../images/productImages/beauty6.jpg"),
//     sale: 15,
//     shopkeeper: "Dior",
//   },
//   {
//     id: 7,
//     category: "Beauty",
//     itemName: "Mascarra kit",
//     description: "some description",
//     price: 1000,
//     image: require("../images/productImages/beauty7.jpg"),
//     sale: 0,
//     shopkeeper: "Dior",
//   },
// ];

export const categories = [
  {
    id: 1,
    name: "Salon",
    image: require("../images/categoriesImages/salon.jpg"),
  },
  {
    id: 2,
    name: "Massage",
    image: require("../images/categoriesImages/massage.jpg"),
  },
  {
    id: 3,
    name: "Repairs",
    image: require("../images/categoriesImages/repair.jpg"),
  },
  {
    id: 4,
    name: "Cleaning",
    image: require("../images/categoriesImages/cleaning.jpg"),
  },
  {
    id: 5,
    name: "Home\nProjects",
    image: require("../images/categoriesImages/home-projects.jpg"),
  },
];
